### ISSUE TITLE
Nginx 1.13.1 SPDY Patch error

### ISSUE THREAD

**Issue by you990808** [cloudflare/sslconfig#70]
In nginx 1.13.1, Cloudflare's spdy patch didn't work.How can I use it?

**Comment by Injust** [comment]
Make sure you're using nginx__1.11.11_http2_spdy.patch, which should work fine with 1.13.1

**Comment by you990808** [comment]
Oh.I'm try to use openssl 1.1.1 dev but patch does not support that openssl version.Thanks.I will use openssl 1.1.0

**Comment by you990808** [comment]
-o objs/src/http/ngx_http_request_body.o 
src/http/ngx_http_request_body.c
src/http/ngx_http_request_body.c: In function ‘ngx_http_discard_request_body’:
src/http/ngx_http_request_body.c:529:49: error: ‘post_handler’ undeclared (first use in this function)
rc = ngx_http_spdy_read_request_body(r, post_handler);
^
src/http/ngx_http_request_body.c:529:49: note: each undeclared identifier is reported only once for each function it appears in
src/http/ngx_http_request_body.c:530:9: error: label ‘done’ used but not defined
goto done;
^
make[1]: *** [objs/src/http/ngx_http_request_body.o] Error 1
make[1]: Leaving directory `/usr/src/nginx-1.13.0'
make: *** [build] Error 2
This error has occurred

**Comment by Injust** [comment]
My bad, are you using the new unmerged patch in #66?

**Comment by you990808** [comment]
No.I use this patch.
https://github.com/cloudflare/sslconfig/blob/master/patches/nginx__1.11.11_http2_spdy.patch

**Comment by Injust** [comment]
Try using https://github.com/cloudflare/sslconfig/blob/5930c628d475023de6d224d0733a3a2a08b829fe/patches/nginx__1.13.0_http2_spdy.patch

**Comment by you990808** [comment]
That patch work perfectly.Thanks @Injust
